---

- hosts: swarm-manager
  become: yes

  pre_tasks:
    - include: tasks/pre.yml

  roles:
    - role: swarm-head
      tags: swarm-head

  post_tasks:
    - include: tasks/post.yml 

- hosts: swarm-workers
  become: yes

  pre_tasks:
    - include: tasks/pre.yml

  roles:
    - role: swarm-worker
      tags: swarm-worker

  post_tasks:
    - include: tasks/post.yml
