---
# tasks file for swarm-head

- name: initialize swarm
  command: docker swarm init
  args:
    creates: /var/lib/docker/swarm/state.json

- name: register swarm manager token
  command: docker swarm join-token -q manager
  register: swarm_token_manager
  changed_when: false

- name: register swarm worker token
  command: docker swarm join-token -q worker
  register: swarm_token_worker
  changed_when: false

#- debug: var=swarm_token_manager.stdout
#- debug: var=swarm_token_worker.stdout
